spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MatiasCermak/config-server-ecommerce-properties.git
server:
  port: 9000